import sys
import json
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch

def generate_certificate(data, output_path):
    # Setup document
    doc = SimpleDocTemplate(output_path, pagesize=A4, rightMargin=50, leftMargin=50, topMargin=50, bottomMargin=50)
    styles = getSampleStyleSheet()
    
    # Custom Styles
    hospital_name_style = ParagraphStyle(
        'HospitalName',
        parent=styles['Heading1'],
        fontSize=26,
        textColor=colors.HexColor("#ED2024"),
        alignment=1,
        spaceAfter=5
    )
    
    tagline_style = ParagraphStyle(
        'Tagline',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.grey,
        alignment=1,
        spaceAfter=20
    )
    
    cert_title_style = ParagraphStyle(
        'CertTitle',
        parent=styles['Heading1'],
        fontSize=22,
        textColor=colors.black,
        alignment=1,
        spaceBefore=30,
        spaceAfter=30,
        underlineWidth=1
    )
    
    body_style = ParagraphStyle(
        'BodyStyle',
        parent=styles['Normal'],
        fontSize=12,
        leading=18,
        alignment=4 # Justified
    )
    
    footer_style = ParagraphStyle(
        'FooterStyle',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.grey,
        alignment=1
    )

    content = []

    # 1. Hospital Header
    content.append(Paragraph("MediAI Hospital Suite", hospital_name_style))
    content.append(Paragraph("A Step Towards Intelligent Healthcare", tagline_style))
    content.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey, spaceBefore=0, spaceAfter=20))

    # 2. Certificate Title
    cert_type = data.get('cert_type', 'MEDICAL CERTIFICATE').upper()
    content.append(Paragraph(cert_type, cert_title_style))

    # 3. Main Body
    patient_name = data.get('patient_name', '[Patient Name]')
    doctor_name = data.get('doctor_name', '[Doctor Name]')
    current_date = datetime.now().strftime("%d %B, %Y")
    
    # Default template for a "Sick Note"
    body_text = f"""
    This is to certify that <b>{patient_name}</b> has been under my medical care and was 
    examined by me on <b>{current_date}</b>.
    <br/><br/>
    Based on the clinical examination, I have advised <b>{patient_name}</b> to take medical 
    leave from <b>{data.get('start_date', '[Start Date]')}</b> to <b>{data.get('end_date', '[End Date]')}</b> 
    due to <b>{data.get('reason', 'medical reasons')}</b>.
    <br/><br/>
    I further certify that the patient is expected to be fit to resume normal duties on 
    <b>{data.get('fitness_date', '[Fitness Date]')}</b>.
    """
    
    # Custom body if provided
    if data.get('custom_body'):
        body_text = data.get('custom_body').replace('\n', '<br/>')

    content.append(Paragraph(body_text, body_style))
    content.append(Spacer(1, 1*inch))

    # 4. Signature Section
    sig_data = [
        [
            Paragraph(f"<b>Date:</b> {current_date}<br/><b>Place:</b> MediAI Medical Center", body_style),
            Paragraph(f"<b>__________________________</b><br/><b>Dr. {doctor_name}</b><br/>Authorized Medical Practitioner", body_style)
        ]
    ]
    
    sig_table = Table(sig_data, colWidths=[2.5*inch, 3*inch])
    sig_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'BOTTOM'),
        ('ALIGN', (1,0), (1,0), 'RIGHT'),
    ]))
    content.append(sig_table)

    # 5. Footer
    content.append(Spacer(1, 1.5*inch))
    content.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey))
    footer_text = "This certificate is generated by MediAI Hospital Suite. Verification ID: " + data.get('verify_id', 'MEDIAI-' + datetime.now().strftime("%Y%m%d%H%S"))
    content.append(Paragraph(footer_text, footer_style))

    doc.build(content)

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python generate_certificate.py <json_data> <output_path>")
        sys.exit(1)
    
    try:
        data_json = sys.argv[1]
        out_path = sys.argv[2]
        data = json.loads(data_json)
        generate_certificate(data, out_path)
        print(f"SUCCESS:{out_path}")
    except Exception as e:
        print(f"ERROR:{str(e)}")
        sys.exit(1)
